name: build

permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '0 7 * * 1'

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 7
    strategy:
      fail-fast: true
      matrix:
        go: ['>=1.20.0']

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Lint
        run: make lint

      - name: Go Format
        run: make format && git diff --exit-code

      - name: Go Vet
        run: make vet

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Build
        run: go build -o /dev/null ./...

      - name: Go Test
        run: make test
